version: '3.9'

services:
  mongo:
    container_name: mongo-for-fastify
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27019:27017'
  database:
    container_name: postgres-for-fastify
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PSQL_HISTFILE=/root/log/.psql_history
      - POSTGRES_DB=postgres
    ports:
      - '5559:5432'

